//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateConfigCustomAction.ApplicationSettingsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicationSettingsService.IApplicationSettings")]
    public interface IApplicationSettings {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationSettings/GetApplicationSettings", ReplyAction="http://tempuri.org/IApplicationSettings/GetApplicationSettingsResponse")]
        System.Collections.Generic.List<ApplicationConfigSettings.Setting> GetApplicationSettings(int applicationID, ApplicationConfigSettings.EnvironmentType env);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationSettingsChannel : UpdateConfigCustomAction.ApplicationSettingsService.IApplicationSettings, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationSettingsClient : System.ServiceModel.ClientBase<UpdateConfigCustomAction.ApplicationSettingsService.IApplicationSettings>, UpdateConfigCustomAction.ApplicationSettingsService.IApplicationSettings {
        
        public ApplicationSettingsClient() {
        }
        
        public ApplicationSettingsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationSettingsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationSettingsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationSettingsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ApplicationConfigSettings.Setting> GetApplicationSettings(int applicationID, ApplicationConfigSettings.EnvironmentType env) {
            return base.Channel.GetApplicationSettings(applicationID, env);
        }
    }
}
