// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using System.Collections.Generic;
using System.Xml;

namespace UpdateConfigCustomAction
{
    public partial class configUpdaterTest
    {

        [TestMethod]
        public void SetConnectionStringValueTest()
        {
            List<string> TestLog = new List<string>();
            configUpdater target = new configUpdater(TestConfigFile);
            const string connectionStringName = "constring1";
            const string encryptedConnectionstringValue = "jqEbONyGO/8RkT+as++JfaZ4ylwmy/aZGa82fFg4DdVbJ0I+Asw6xpzfcpwx+yLzwkldXvoT8Y2RMXek/jwe/Xm0MxoaCOK9V3JPybfqLjsy9Dcb0FXoMDEZpFbA/S9810AU9flBpveHQ7XbGe/4LW0N9Hs+5r1wEdNDrj9fZ0g=";
            bool actual = target.SetConnectionStringValue(connectionStringName, encryptedConnectionstringValue, TestLog.Add);
            Assert.AreEqual(true, actual);

            XmlNode node = TestConfigFile.SelectSingleNode("//connectionStrings");
            XmlElement Elem = (XmlElement)node.SelectSingleNode(String.Format("//add[@name='{0}']", connectionStringName));
            string attribute = Elem.GetAttribute("connectionString");
            Assert.AreEqual(encryptedConnectionstringValue, attribute);
        }
    }
}
