// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System.Preparations;
using Microsoft.Moles.Framework.Moles;

namespace UpdateConfigCustomAction
{
    public partial class configUpdaterTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(configUpdaterTest))]
        public void ConstructorTest()
        {
            configUpdater configUpdater;
            configUpdater = this.Constructor01();
            Assert.IsNotNull((object)configUpdater);
            Assert.AreEqual<string>("", configUpdater.docName);
            Assert.IsNotNull(configUpdater.configFile);
            Assert.IsNotNull(configUpdater.configFile.Implementation);
            Assert.AreEqual<bool>(false, configUpdater.configFile.PreserveWhitespace);
        }
[TestMethod]
[PexGeneratedBy(typeof(configUpdaterTest))]
[Ignore]
[PexDescription("this test requires to run under the Pex profiler in order to reproduce")]
[PexRaisedException(typeof(MoleNotImplementedException))]
[PexNotReproducible]
[HostType("Moles")]
public void Constructor01ThrowsMoleNotImplementedException350()
{
    configUpdater configUpdater;
    AppDomainPreparation.Prepare();
    configUpdater = this.Constructor01();
}
    }
}
