// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using System.Collections.Generic;
using System.Xml;

namespace UpdateConfigCustomAction
{
    public partial class configUpdaterTest
    {

        [TestMethod]
        public void SetServiceEndPointValueTest()
        {
            List<string> TestLog = new List<string>();
            configUpdater target = new configUpdater(TestConfigFile);
            const string endpointName = "DebtService.DebtService";
            const string endpointAddress = "net.msmq://test/private/debtcollection.svc";
            bool actual = target.SetServiceEndPointValue(endpointName, "address", endpointAddress, TestLog.Add);
            Assert.AreEqual(true, actual);

            XmlNode node = TestConfigFile.SelectSingleNode("//services");
            XmlElement Elem = (XmlElement)node.SelectSingleNode(String.Format("//service[@name='{0}']/endpoint", endpointName));
            string attribute = Elem.GetAttribute("address");
            Assert.AreEqual("net.msmq://test/private/debtcollection.svc", attribute);
        }
    }
}
