// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using System.Collections.Generic;
using System.Xml;

namespace UpdateConfigCustomAction
{
    public partial class configUpdaterTest
    {

        [TestMethod]
        public void SetServiceBaseAddressValue()
        {
            List<string> TestLog = new List<string>();
            configUpdater target = new configUpdater(TestConfigFile);
            const string configSectionName = "DebtService.DebtService";
            const string attributeName = "baseAddress"; // 
            const string attributeValue = "http://testserver:8742/";
            bool actual = target.SetServiceBaseAddress(configSectionName, attributeName, attributeValue, TestLog.Add);
            Assert.AreEqual(true, actual);

            XmlNode node = TestConfigFile.SelectSingleNode(string.Format("//service[@name='{0}']", configSectionName));
            XmlElement Elem = (XmlElement)node.SelectSingleNode("//host//baseAddresses//add");
            string attribute = Elem.GetAttribute(attributeName);
            Assert.AreEqual("http://testserver:8742/", attribute);

        }
    }
}
