// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using ApplicationConfigSettings;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System.Preparations;
using Microsoft.Moles.Framework.Moles;

namespace UpdateConfigCustomAction
{
    public partial class CustomActionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CustomActionsTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetApplicationSettings289()
{
    List<Setting> list;
    list = this.GetApplicationSettings
               ((Action<string>)null, (EnvironmentType)0);
}
[TestMethod]
[PexGeneratedBy(typeof(CustomActionsTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void GetApplicationSettings28903()
{
    List<Setting> list;
    list = this.GetApplicationSettings
               ((Action<string>)null, (EnvironmentType)0);
}
[TestMethod]
[PexGeneratedBy(typeof(CustomActionsTest))]
[Ignore]
[PexDescription("this test requires to run under the Pex profiler in order to reproduce")]
[PexRaisedException(typeof(MoleNotImplementedException))]
[PexNotReproducible]
[HostType("Moles")]
public void GetApplicationSettingsThrowsMoleNotImplementedException121()
{
    List<Setting> list;
    AppDomainPreparation.Prepare();
    list = this.GetApplicationSettings
               ((Action<string>)null, (EnvironmentType)0);
}
    }
}
